version: '3'

services:
    strapi:
        container_name: just-view-cms
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - '1337:1337'
